Supporting sorting by multiple columns
cylondata/cylon pull request #330
Opened 2021-02-25 18:46 UTC by chathurawidanage

2021-02-25 19:34 UTC, nirandaperera commented
@chathurawidanage I think the tests are failing because the csv1_0.csv has been changed! :-) could you please change that?

2021-02-25 20:02 UTC, chathurawidanage commented
Yeah. I tried to revert that based on what's available in commit history.. But not sure whether there was two 41s in the original file.

2021-02-27 11:39 UTC, vibhatha commented
Can we add some Python test cases for new options?

2021-02-28 15:49 UTC, nirandaperera requested changes

2021-02-28 15:49 UTC, nirandaperera commented on cpp/src/cylon/arrow/arrow_comparator.cpp
> +    return (diff > 0) - (diff < 0);
shall we add a comment here with a link to the bit twiddling hacks site?
https://graphics.stanford.edu/~seander/bithacks.html#CopyIntegerSign

2021-02-28 15:49 UTC, nirandaperera commented on cpp/src/cylon/arrow/arrow_comparator.cpp
>    this->tables = tables;
shall we move these to the initializer list?

2021-02-28 15:49 UTC, nirandaperera commented on cpp/src/cylon/arrow/arrow_kernels.cpp
> +    array->GetView(0);
I believe this is not required

2021-02-28 15:49 UTC, nirandaperera commented on cpp/src/cylon/arrow/arrow_kernels.hpp
> +                                      const std::vector<bool> &ascending);
should we add a default value for ascending here?

2021-02-28 15:51 UTC, nirandaperera commented
@chathurawidanage from hereon, let's not send PRs from your master branch. It could get really ugly because we are doing  squash and merge :slightly_smiling_face:

2021-03-02 21:17 UTC, nirandaperera approved these changes

2021-03-02 21:18 UTC, merged