Indexing improvement
cylondata/cylon pull request #394
Opened 2021-04-14 12:49 UTC by vibhatha

2021-04-14 17:03 UTC, nirandaperera requested changes

2021-04-14 17:03 UTC, nirandaperera commented on cpp/src/cylon/table.hpp
> +  Status Set_ArrowIndex(std::shared_ptr<cylon::BaseArrowIndex> &index, bool drop_index);
rename to SetArrowIndex

2021-04-14 17:22 UTC, vibhatha commented on cpp/src/cylon/indexing/index.cpp
>    auto unique_arr = result.ValueOrDie();
+1
need to refactor this method to get the index as an output and set the return as Status

2021-04-15 12:20 UTC, vibhatha commented on cpp/src/cylon/indexing/index.hpp
> +	return Status::OK();
since the class is templated, can we move this to CPP?

2021-04-15 21:41 UTC, vibhatha commented on cpp/src/cylon/indexing/index_utils.cpp
> +	case arrow::Type::TIME64:break;
Will add the support to temporal types and binaries in another PR. This requires re-writing the underlying HashIndexing Kernel to support the types.

2021-04-16 20:34 UTC, merged